language: cpp

sudo: false

compiler:
  - clang

cache: apt

addons:
  apt:
    packages:
    - libstdc++-4.8-dev
    - clang-3.5

script:
  - make -j4 ckati
  - ruby runtest.rb -c
  - ruby runtest.rb -c -n
 