language: cpp

sudo: false

compiler:
  - clang

cache: apt

addons:
  apt:
    packages:
    - clang-3.5

script:
  - make -j4 ckati CXX=clang++-3.5
  - ruby runtest.rb -c
  - ruby runtest.rb -c -n
 